name: DISA-STIG-Remediation
on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Target env"
        type: choice
        options: [dev, staging, prod]
        default: dev
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: my-step
        run: echo "Deploying to ${{ inputs.environment }}
